### ISSUE TITLE
tests from subfolders

### ISSUE THREAD

**Issue by ronald-cognite** [Selminha/testcafe-runner#10]
Hi! Thanks for making this great extension :) 

I'm only having one issue with it: it seems to only find the tests in the last subfolder:
our structure:

```
tests/set1/homepage.testcafe.test
tests/set1/detailpage.testcafe.test

tests/set2/homepage.testcafe.test
tests/set2/detailpage.testcafe.test
```

It finds only the tests in the last folder (set2 in the example above)

Thanks!

**Comment by Selminha** [comment]
Hi, sorry for taking too long to answer.
Looking at your example, I don't know how the first folder works as testlatte only search for files with extension ".js" and ".ts". 
The next version of testlatte will accept accept javascript, typescript, coffeescript and TestCafe Studio﻿ tests (.testcafe files) files, that is the files testcafe supports, according to the documentation. (https://testcafe.io/documentation/402639/reference/command-line-interface#file-pathglob-pattern).
Please, try to change the extension of the files to see if it fix the issue.

Best Regards!

**Comment by Selminha** [comment]
close for inactivity.
