### ISSUE TITLE
Couldn't execute Testcafe tests

### ISSUE THREAD

**Issue by geeksreeni** [Selminha/testcafe-runner#12]
Hi while executing testcafe testing from testlatte below are the errors:
seneca@sreenis-ubuntu:~/Sreenivas/Cy_CodeBase/Cyglass-UI-Automation$ cd /home/seneca/Sreenivas/Cy_CodeBase/Cyglass-UI-Automation; npx --no-install /home/seneca/Sreenivas/Cy_CodeBase/Cyglass-UI-Automation/node_modules/testcafe/bin/testcafe.js chrome /home/seneca/Sreenivas/Cy_CodeBase/Cyglass-UI-Automation/UI/tests/Navigations/LoginPageTests.ts --test "Successful Login Verification Test" 
npm ERR! code ENOTDIR
npm ERR! syscall open
npm ERR! path /home/seneca/Sreenivas/Cy_CodeBase/Cyglass-UI-Automation/node_modules/testcafe/bin/testcafe.js/package.json
npm ERR! errno -20
npm ERR! ENOTDIR: not a directory, open '/home/seneca/Sreenivas/Cy_CodeBase/Cyglass-UI-Automation/node_modules/testcafe/bin/testcafe.js/package.json'

in command line i could execute the tests.

my configurations:
![image](https://user-images.githubusercontent.com/82573054/123088526-74a80d80-d443-11eb-8114-243603ece161.png)

**Comment by Selminha** [comment]
Hello,
Are you using testcafe installed locally or globally?

**Comment by geeksreeni** [comment]
tc installed globally and locally
below is the package.json
{
  "name": "ui-automation",
  "version": "1.0.0",
  "description": "UI Auomation Project",
  "main": "index.js",
  "scripts": {
    "test-dev-smoke": "testcafe tests/ --environment=dev --test-meta smokeTest=true",
    "test-dev-regression": "testcafe tests/ --environment=dev --test-meta regressionTest=true",
    "test-staging-smoke": "testcafe tests/ --environment=staging --test-meta smokeTest=true",
    "test-staging-regression": "testcafe tests/ --environment=staging --test-meta regressionTest=true"
  },
  "author": "Sreenivas Parimi",
  "license": "ISC",
  "devDependencies": {
    "@elastic/elasticsearch": "^7.13.0",
    "axios": "^0.21.1",
    "testcafe": "^1.14.2"
  }
}

**Comment by geeksreeni** [comment]
@Selminha can you help me on this.

**Comment by Selminha** [comment]
Can you send the path your testcafe is installed?

**Comment by Selminha** [comment]
You said that you can execute the tests in the command line, can you send the command line that is working?

**Comment by geeksreeni** [comment]
As my package.json has scripts test-dev-smoke
npm run test-dev-smoke is working for me on command line

**Comment by Selminha** [comment]
> 
> 
> As my package.json has scripts test-dev-smoke
> npm run test-dev-smoke is working for me on command line

Have you tried to put the command line arguments on the testlatte configuration?
If not you need to go to testlatte settings->custom arguments->edit in settings.json
And in the json you put your arguments (--environment=dev --test-meta smokeTest=true) in the testlatte.customArguments, like the images below.

Please let me know if it works.

![Custom arguments](https://user-images.githubusercontent.com/8799615/124134994-cb23d600-da59-11eb-9a56-2061e1590a5a.png)
![Custom arguments json](https://user-images.githubusercontent.com/8799615/124135007-ce1ec680-da59-11eb-938b-ffcf24fff895.png)

**Comment by geeksreeni** [comment]
I have tried it, but no luck.
below is settings.json
![image](https://user-images.githubusercontent.com/82573054/124226672-1e178f00-db27-11eb-9dae-7a91bd88ec1c.png)

here is the error screenshot:
![image](https://user-images.githubusercontent.com/82573054/124226862-6040d080-db27-11eb-9357-a1cc728ac806.png)


Tc is executing with: Using locally installed version of TestCafe.

**Comment by Selminha** [comment]
Hi,
Sorry I couldn't reproduce your issue and find exactly what is happening, I'm thinking it can be a issue with packages version, I have updated all the packages of testlatte and published a new version, please try to run with this new version and let me know if it works.

Best Regards.

**Comment by Selminha** [comment]
Close for inactivity.
