### ISSUE TITLE
Support Custom Test Classes

### ISSUE THREAD

**Issue by pschmolke** [Selminha/testcafe-runner#13]
I have the following problem that I have written myself a wrapper function MyTest which hooks into testcafe's Test class to achieve various custom hooks, e.g. logging monitoring, injection of meta information. But, logically, the testlatte plugin does therefore not recognize the Tests itself. The fixtures are listed as normal but sadly without any test.

Is it possible to add a settings option where I can specify a custom function/class that provides the test? Or make it not so picky?

Versions:
| lib | version |
|---------|---------|
| testcafe | 1.17.1 |
| typescript | 4.5.2 |

**Comment by Selminha** [comment]
Hi

In order to help you I need more information, can you provide an example of what you are trying to achieve? More details about the settings option you want can help too.

Best Regards

Selma

**Comment by Selminha** [comment]
Close for inactivity
