### ISSUE TITLE
1.5.0 testOutline.runTest

### ISSUE THREAD

**Issue by carlgordon** [Selminha/testcafe-runner#3]
With the new 1.5.0 update I am now getting this error... 

`Error running command testOutline.runTest: Running the contributed command: 'testOutline.runTest' failed.. This is likely caused by the extension that contributes testOutline.runTest.`

I had to roll the plugin back to 1.4.0 to make it work again

**Comment by Selminha** [comment]
Issue fixed on version 1.5.1, please let me know if the problem persists.
