### ISSUE TITLE
Causes CPU to run at 100%

### ISSUE THREAD

**Issue by shyaniv7** [Selminha/testcafe-runner#5]
After having issues with VSCode running my CPU to the point where my laptop sounds like its about to take off, I disabled extensions one by one. Once `testlate` was disabled my CPU went back to normal levels.

I did not debug the cause in the package itself but I am reporting it as an issue here so that others would be aware of it.

Cheers!

**Comment by Selminha** [comment]
Hi, I'm already aware of this problem and have been working on a fix.

**Comment by Selminha** [comment]
Version 2.0.0 will probably fix this issue, can you please enable and update TestLatte to check if it was solved?
Reopen this issue if the problem persists.

Thank you for your feedback.
